[project]
name = "senai-ai-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.14.3",
    "azure-identity>=1.25.3",
    "easyocr>=1.7.2",
    "faiss-cpu>=1.15.0",
    "google-generativeai>=0.8.6",
    "groq>=1.6.0",
    "imageio[pyav]>=2.37.4",
    "openai>=3.0.0",
    "pypdf>=6.16.1",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.7.0",
    "streamlit>=1.61.1",
]
